config/routes.rb
Rails.application.routes.draw do

  resources :carts
  resources :line_items

  resources :brands do
    resources :cars do
      resources :products do
        resources :types do
          resources :items
        end
      end
    end
  end

  root 'pages#Home'

  get 'pages/About_Us'

  get 'pages/Contact_Us'

  get 'pages/Blog'

  get 'pages/FAQs'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy



  def add_item(item_id)

    current_line_item = line_items.find_by(:item_id => item_id)

    if current_line_item
      current_line_item.quantity += 1
    else
      current_line_item = line_items.new(:item_id => item_id)
    end

    return current_line_item

  end

  #def total
  #  - sum = 0
  #  - line_items.each {|li| sum += li.total}
  #  - sum
  #end
  def grand_total

    line_items.to_a.sum { |item| item.total_price }
    #line_items.each |line_item|
    #  {
    #      sum +=line_item.total_price
    #
    #  }
    #
    #end

  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def show
    @cart= Cart.find(params[:id])
  end

  private

  def invalid_cart

    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: 'Invalid cart'

  end

  #def destroy
  #  @cart = Cart.find(params[:id])
  #  if (@cart.id == session[:cart_id])
  #    @cart.destroy
  #    session[:cart_id] = nil
  #  end
  #  redirect_to carts_path
  #end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>





<div class="col-md-9 panel panel-default  " >
  <div class="col-md-12 ">
    <div class="cart-list">
            <% @cart.line_items.each do |line_item| %>
            <div class="row">
                <div class="col-md-3 ">

                  <%= image_tag line_item.item.image_url,size: "100x100" %>

                </div>
                <div class="col-md-9">
                  <div >
                    <b><%= link_to line_item.item.name,brand_car_product_type_item_path(:id=>line_item.item.id,
                                                                                        :item_id=>line_item.item.id,
                                                                                        :type_id=>line_item.item.type.id,
                                                                                        :product_id=>line_item.item.type.product.id,
                                                                                        :car_id=>line_item.item.type.product.car.id,
                                                                                        :brand_id =>line_item.item.type.product.car.brand.id) %></b>
                    <div class=" pull-right">

                        <%= link_to 'Remove',line_item_path(:line_item_id => line_item.id), method: :delete,
                             data: { confirm: 'Are you sure?' } ,:class => "delete-cart" %>

                    </div>

                    <br>
                    <b>Price :</b> Rs.<%= line_item.item.price  %>
                    <br>
                    <b> Quantity : </b> <%= line_item.quantity %></li>

                    <br>
                    <b>Manufacturer: </b><%= line_item.item.manufacturer %>
                    <br>

                   <div class="total-price pull-right"><b> TOTAL : </b> Rs. <%= line_item.total_price  %> </div>
                  </div>

                </div>
            </div>
            <div class="">
                <hr>
            </div>
            <% end %>
            <div class="grand-total pull-right ">
                <b> GRAND TOTAL : </b> Rs.<%= @cart.grand_total   %>
            </div>
    </div>

  </div>
</div>

<div class="col-md-3">
  <% @cart.line_items.each do |line_item| %>

      <%= image_tag line_item.item.image_url,size: "50x50" %>

      <b><%= link_to line_item.item.name,brand_car_product_type_item_path(:id=>line_item.item.id,
                                                                          :item_id=>line_item.item.id,
                                                                          :type_id=>line_item.item.type.id,
                                                                          :product_id=>line_item.item.type.product.id,
                                                                          :car_id=>line_item.item.type.product.car.id,
                                                                          :brand_id =>line_item.item.type.product.car.brand.id) %></b>

      <div class="">
        <hr>
      </div>
      <br>
<% end %>
  <div class="total-price  "><b> SubTotal : </b> Rs.<%= @cart.grand_total   %> </div>
    <br>
  <div class="btn btn-block btn-success "> Checkout >>></div>

</div>