config/routes.rb
Rails.application.routes.draw do

  resources :carts
  resources :line_items

  resources :brands do
    resources :cars do
      resources :products do
        resources :types do
          resources :items
        end
      end
    end
  end

  root 'pages#Home'

  get 'pages/About_Us'

  get 'pages/Contact_Us'

  get 'pages/Blog'

  get 'pages/FAQs'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :type
  #validates :name , :presence => true , :uniqueness => true,uniqueness: { case_sensitive: false}
  #validates :image_url, allow_blank: false, format: {
  #    with: %r{\.(gif|jpg|png)\Z}i,
  #    message: 'must be a URL for GIF, JPG or PNG image.', :presence => true
  #}
  #validates :price, :numericality => {:greater_than_or_equal_to => 0.01}, :presence => true
  #validates :description , :presence => true
  #validates :manufacturer, :presence => true

  has_many :line_items
  before_destroy 'ensure_not_referenced_by_any_line_item' # ensure that there are no line items referencing this product




  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_id, :only=> [:index, :create, :show]

  def index
    @item = Item.new
  end

  def show
    @item = @type.items.find(params[:id])
  end

  def new
  end

  def create
    @item = @type.items.new(item_params)
    if @item.save
      redirect_to brand_car_product_type_items_path(:type_id => @type.id), :notice => "Succefully created...!!!"
    else
      redirect_to brand_car_product_type_items_path(:type_id => @type.id),:notice => "All fields are manadatory...!!!"

      #format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  def update
  end

  def delete
  end

  private

  def set_id

    @brand = Brand.find(params[:brand_id])
    @car = Car.find(params[:car_id])
    @product = Product.find(params[:product_id])
    @type = Type.find(params[:type_id])
    #
    #@brand = Brand.find(params[:brand_id])
    #@car = @brand.cars.find(params[:car_id])
    #@product = @car.products.find(params[:product_id])
    #@type = @product.types.find(params[:type_id])
  end

  def item_params
    params.require(:item).permit(:name,:image_url,:price,:manufacturer,:description,:type_id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/delete.html.erb
<h1>Items#delete</h1>
<p>Find me in app/views/items/delete.html.erb</p>

app/views/items/index.html.erb
<% if @item.errors.any? %>
    <div id="error_explanation">
      <h3 style="color: red">
        <%= pluralize(@item.errors.count, "error") %> prohibited this Product from being saved:</h3>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= flash[:notice] %>

<%= link_to "Add new Item to SELL!!!" %>
<%= form_for([@brand,@car,@product,@type,@item])  do |f|%>
    <%=  %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
<br>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <br>
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.submit %>

<% end %>

<% @type.items.each do |item| %>

    <%= link_to "#{item.name}", brand_car_product_type_item_path(:id=> item.id) %><br>
    <%= item.image_url %><br>
    <%= item.price %><br>
    <%= item.description %><br>
    <%= item.manufacturer %><br>


<% end %>

app/views/items/show.html.erb
<div class="col-md-3">
  <div class="panel panel-default typesbar">
    <div class="product-sidebar">
      <% @car.products.each do |product| %>
          <div class="sidebar-menu">
            <td><%= link_to "#{product.name}", brand_car_product_types_path(:brand_id => @brand.id, :car_id => @car.id , :product_id => product.id )  %> </td>
            <br>
          </div>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-9 panel panel-default  " >
  <div class="col-md-12">
    <div class="col-md-3 ">
      <%= image_tag @item.image_url,size: "100x100" %>

    </div>
    <div class="col-md-9">
      <div >
        <b><%=@item.name%></b>
        <br>
        <b>Price :</b> Rs.<%= @item.price  %>
        <br>
        <b>Manufacturer: </b><%= @item.manufacturer %>
        <br>
        <b>Description: </b> <%= @item.description %>
        <br>

        <div class="btn">
          <%= button_to 'Add to Cart', line_items_path(item_id: @item.id) , class: "btn-success" %>
        </div>
      </div>

    </div>



  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>