config/routes.rb
Rails.application.routes.draw do

  resources :carts
  resources :line_items

  resources :brands do
    resources :cars do
      resources :products do
        resources :types do
          resources :items
        end
      end
    end
  end

  root 'pages#Home'

  get 'pages/About_Us'

  get 'pages/Contact_Us'

  get 'pages/Blog'

  get 'pages/FAQs'

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :cars
  #validates :name , :presence => true,uniqueness: { case_sensitive: false}
  ##validates :name, :uniqueness => true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = Brand.all
  end
  def show
    @car = Car.new

  end

  def new
    @brand = Brand.new
  end

  def edit
  end
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name, :history )
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :history %><br>
    <%= f.text_area :history %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <!--<th>History</th>-->
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to "#{brand.name}",brand %></td>
        <!--<td><%#= brand.history %></td>-->
        <td><%= link_to 'Edit  ', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>History:</strong>
  <%= @brand.history %>
</p>

<p>
  <%= link_to 'Add new Car', "#new" %>

<div id="new" style="display: inline">
  <%= form_for([@brand,@car]) do|f| %>
      <%= f.hidden_field :brand_id %>

      <div class="field">
        <%= f.label :name %> :
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>

  <% end %>

</div>
</p>

<p>
  <%= @brand.cars.each do|car|  %>
    <%= link_to "#{car.name}",brand_car_products_path(:brand_id => @brand.id,:car_id => car.id ) %><br>
  <% end %>

</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>