config/routes.rb
Rails.application.routes.draw do

  resources :carts
  resources :line_items

  resources :brands do
    resources :cars do
      resources :products do
        resources :types do
          resources :items
        end
      end
    end
  end

  root 'pages#Home'

  get 'pages/About_Us'

  get 'pages/Contact_Us'

  get 'pages/Blog'

  get 'pages/FAQs'

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :cars
  #validates :name , :presence => true,uniqueness: { case_sensitive: false}
  ##validates :name, :uniqueness => true
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :brand

  has_many :products
  #validates :name ,:presence => true,uniqueness: { case_sensitive: false}
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy



  def add_item(item_id)

    current_line_item = line_items.find_by(:item_id => item_id)

    if current_line_item
      current_line_item.quantity += 1
    else
      current_line_item = line_items.new(:item_id => item_id)
    end

    return current_line_item

  end

  #def total
  #  - sum = 0
  #  - line_items.each {|li| sum += li.total}
  #  - sum
  #end
  def grand_total

    line_items.to_a.sum { |item| item.total_price }
    #line_items.each |line_item|
    #  {
    #      sum +=line_item.total_price
    #
    #  }
    #
    #end

  end
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :type
  #validates :name , :presence => true , :uniqueness => true,uniqueness: { case_sensitive: false}
  #validates :image_url, allow_blank: false, format: {
  #    with: %r{\.(gif|jpg|png)\Z}i,
  #    message: 'must be a URL for GIF, JPG or PNG image.', :presence => true
  #}
  #validates :price, :numericality => {:greater_than_or_equal_to => 0.01}, :presence => true
  #validates :description , :presence => true
  #validates :manufacturer, :presence => true

  has_many :line_items
  before_destroy 'ensure_not_referenced_by_any_line_item' # ensure that there are no line items referencing this product




  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart


  def total_price
    item.price * quantity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :car
  has_many :types
  #
  #validates :name ,:presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :product
  has_many :items
  #validates :name , :presence => true ,uniqueness: { case_sensitive: false}
  #

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController


  def delete
  end


  def create
    @brand = Brand.find(params[:brand_id])
    @cars = @brand.cars.new(car_params)

    if @cars.save
      redirect_to brand_path(@brand),:notice=> "Success"
    else
      redirect_to brand_path(@brand),:notice=> "Name should br unique"

    end

  end

  def update

  end
  private

  def car_params
    params.require(:car).permit(:name,:brand_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def show
    @cart= Cart.find(params[:id])
  end

  private

  def invalid_cart

    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: 'Invalid cart'

  end

  #def destroy
  #  @cart = Cart.find(params[:id])
  #  if (@cart.id == session[:cart_id])
  #    @cart.destroy
  #    session[:cart_id] = nil
  #  end
  #  redirect_to carts_path
  #end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_id, :only=> [:index, :create, :show]

  def index
    @item = Item.new
  end

  def show
    @item = @type.items.find(params[:id])
  end

  def new
  end

  def create
    @item = @type.items.new(item_params)
    if @item.save
      redirect_to brand_car_product_type_items_path(:type_id => @type.id), :notice => "Succefully created...!!!"
    else
      redirect_to brand_car_product_type_items_path(:type_id => @type.id),:notice => "All fields are manadatory...!!!"

      #format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  def update
  end

  def delete
  end

  private

  def set_id

    @brand = Brand.find(params[:brand_id])
    @car = Car.find(params[:car_id])
    @product = Product.find(params[:product_id])
    @type = Type.find(params[:type_id])
    #
    #@brand = Brand.find(params[:brand_id])
    #@car = @brand.cars.find(params[:car_id])
    #@product = @car.products.find(params[:product_id])
    #@type = @product.types.find(params[:type_id])
  end

  def item_params
    params.require(:item).permit(:name,:image_url,:price,:manufacturer,:description,:type_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
    @brands  = Brand.all

    @cars = Brand.where("brand_id = ?", Brand.first.id)
    #@cars = Car.all
    @products = Product.all
    #@brand = Brand.find( 1)
    #@cars = @brand.cars.all
    #@car = Car.find( 1)
    #@products = @car.products.all
    @type = Type.first
    @items = @type.items.all
  end

  def About_Us
  end

  def Contact_Us
  end

  def Blog
  end

  def FAQs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autokart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container ">
    <div class="navbar-header " class = "imagee" >
      <%= link_to image_tag('logo.PNG'),'http://autokart.herokuapp.com/' %>

      <%#= link_to image_tag('logo.PNG'),'/' %>

    </div>
    <div class="pull-right">
      <ul>

        <li> <%= link_to 'Login', "#" %> </li>
        <li>  | </li>
        <li> <%= link_to 'SignUp', "#" %></li>

        <li><b>  <%= link_to 'Cart', cart_path(@cart) ,:class => "btn btn-success cart", :onClick => "checkout()" %> </b> </li>

      </ul>
    </div>

  </div>



</div>
<div class="container">
<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/pages/About_Us.html.erb
<h1>Pages#About_Us</h1>
<p>Find me in app/views/pages/About_Us.html.erb</p>

app/views/pages/Blog.html.erb
<h1>Pages#Blog</h1>
<p>Find me in app/views/pages/Blog.html.erb</p>

app/views/pages/Contact_Us.html.erb
<h1>Pages#Contact_Us</h1>
<p>Find me in app/views/pages/Contact_Us.html.erb</p>

app/views/pages/FAQs.html.erb
<h1>Pages#FAQs</h1>
<p>Find me in app/views/pages/FAQs.html.erb</p>

app/views/pages/Home.html.erb
<div class="panel-body panel-default panel searchbar">

<div class="row">
  <div class="col-md-12 tagline">
    Welcome to the coolest way to buy autoparts online...!!!
  </div>
  <hr>
  <div class="col-md-6">

    <div class="panel-default">
                    <div class="autopart-title">
                    Search Parts of Car
                    </div>

            <%= form_for :dynamic do |f| %>
                  <div  class ="col-md-7 input-group form-margin vall">

                      <%= f.collection_select(  :brand_id , @brands.all, :id, :name,{:prompt => '--Select a Brand--'} ,{:class=> "  form-control   " }) %>

                  </div>

                    <%#= f.grouped_collection_select :prop_sub_type_id, PropType.order(:name), :prop_sub_types, :name, :id, :name, :prompt => "-- Select Property Subtype --"  %>


                  <div class="input-group col-md-7 form-margin">

                    <%= f.grouped_collection_select(  :car_id , Brand.order(:name),:cars,:name, :id, :name,{:prompt => '--Select a Car--'} ,{:class=> "  form-control vallcar  "}) %>

                  </div>
                  <div class="input-group col-md-7 form-margin">

                    <%= f.grouped_collection_select( :product_id , Car.order(:name),:products,:name, :id, :name,{:prompt => '--Select a category--'} ,{:class=> "  form-control vallproduct  "}) %>

                  </div>
                  <div class="input-group col-md-7 form-margin">
                       <button type="button" class="btn btn-primary form-margin btn-block" >
                           <div class="submit">
                             Submit
                           </div>
                       </button>
                  </div>
            <% end %>

    </div>
  </div>

      <div class="col-md-6 ">
        <div class="panel-default">
                      <div class="part-title">
                          Search new Car
                      </div>
                      <div class="input-group col-md-7 form-margin">
                        <select class="form-control" name="bootstrap-theme" id="theme_chooser">
                          <option value="">-Select Brand-</option>
                      </select>
                      </div>

                      <div class="input-group col-md-7 form-margin">
                        <select class="form-control" name="bootstrap-theme" id="theme_chooser">
                          <option value="">-Select Model-</option>
                        </select>
                      </div>

                      <div class="input-group col-md-7 form-margin">
                         <button type="button" class="btn btn-primary form-margin btn-block" >
                          Submit
                        </button>
                      </div>
        </div>
      </div>

</div>


</div>
<%= flash[:notice]  %>
<div class="row">



















<% @items.each do |item| %>

    <div class="col-md-4">
      <div class="panel panel-default panel-success panel-item">
        <div class="product-menu">
          <div class="img-responsive">
             <%= image_tag item.image_url,size: "100x100" %>
          </div>
          <br>

          <b>
            <%= link_to "#{item.name}", brand_car_product_type_item_path(:id=> item.id,
                                                                         :item_id=> item.id,
                                                                         :type_id=> item.type.id,
                                                                         :product_id=> item.type.product.id,
                                                                         :car_id=> item.type.product.car.id,
                                                                         :brand_id => item.type.product.car.brand.id) %>
          </b>
          <br><b>Price :</b> Rs.<%= item.price  %>
          <br>
        <b>Manufacturer: </b><%= item.manufacturer %>
        <br><b>Description: </b> <%= truncate(item.description) %>
        </div>
      </div>
    </div>
<% end %>
</div>

<!--truncate("Once upon a time in a world far far away")-->
<!--# => "Once upon a time in a world..."-->

<!--truncate("Once upon a time in a world far far away", length: 17)-->
<!--# => "Once upon a ti..."-->

<!--truncate("Once upon a time in a world far far away", length: 17, separator: ' ')-->
<!--# => "Once upon a..."-->

<!--truncate("And they found that many people were sleeping better.", length: 25, omission: '... (continued)')-->
<!--# => "And they f... (continued)"-->

<!--truncate("<p>Once upon a time in a world far far away</p>")-->
<!--# => "&lt;p&gt;Once upon a time in a wo..."-->

<!--truncate("<p>Once upon a time in a world far far away</p>", escape: false)-->
<!--# => "<p>Once upon a time in a wo..."-->

  <!--truncate("Once upon a time in a world far far away") { link_to "Continue", "#" }-->
  <!--# => "Once upon a time in a wo...<a href="#">Continue</a>"-->